// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrqZyMGnXbegwCQbidEqF1vQzcY4WsjmM',
    appId: '1:760398092419:web:741648cd456edf3fad63b6',
    messagingSenderId: '760398092419',
    projectId: 'degnekcidb',
    authDomain: 'degnekcidb.firebaseapp.com',
    storageBucket: 'degnekcidb.appspot.com',
    measurementId: 'G-C9EB11NG1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx-LKKW-DF_2HEBMhBLydJ1V17ZkwlB-A',
    appId: '1:760398092419:android:8ee7ab3d61f66b80ad63b6',
    messagingSenderId: '760398092419',
    projectId: 'degnekcidb',
    storageBucket: 'degnekcidb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5ScpzR1UjOCQcrY8IZPjXQ2CNi1fJqno',
    appId: '1:760398092419:ios:bc5cf8797f8d6821ad63b6',
    messagingSenderId: '760398092419',
    projectId: 'degnekcidb',
    storageBucket: 'degnekcidb.appspot.com',
    iosBundleId: 'com.example.blog4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5ScpzR1UjOCQcrY8IZPjXQ2CNi1fJqno',
    appId: '1:760398092419:ios:5160ab7cd1459f2fad63b6',
    messagingSenderId: '760398092419',
    projectId: 'degnekcidb',
    storageBucket: 'degnekcidb.appspot.com',
    iosBundleId: 'com.example.blog4.RunnerTests',
  );
}
