// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLyGVAIpEA6zBqziCkp0xFxW6_SGXjxag',
    appId: '1:748075183377:web:aefe0553d98fd70dcbf0b0',
    messagingSenderId: '748075183377',
    projectId: 'fir-blog3-c6ce0',
    authDomain: 'fir-blog3-c6ce0.firebaseapp.com',
    storageBucket: 'fir-blog3-c6ce0.appspot.com',
    measurementId: 'G-K0G0DWPV3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT8SeQ6vNIPL_eG3JBe3g7NWSUVbl0-8w',
    appId: '1:748075183377:android:4535ec38c9c7fa27cbf0b0',
    messagingSenderId: '748075183377',
    projectId: 'fir-blog3-c6ce0',
    storageBucket: 'fir-blog3-c6ce0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUMfyUH_0kOwFr4rhetqtex0FrttmZklg',
    appId: '1:748075183377:ios:7c1c2347a6df6950cbf0b0',
    messagingSenderId: '748075183377',
    projectId: 'fir-blog3-c6ce0',
    storageBucket: 'fir-blog3-c6ce0.appspot.com',
    iosBundleId: 'com.example.blog3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUMfyUH_0kOwFr4rhetqtex0FrttmZklg',
    appId: '1:748075183377:ios:0a17581e951e1655cbf0b0',
    messagingSenderId: '748075183377',
    projectId: 'fir-blog3-c6ce0',
    storageBucket: 'fir-blog3-c6ce0.appspot.com',
    iosBundleId: 'com.example.blog3.RunnerTests',
  );
}
